Repository breez/misty-breez, pull requests merged in 2025-03, with the labels that each got.

#403 ui: darken the theme to match SDK documentation colors
  assets/animations/breez_loader_blue.gif
  assets/animations/breez_loader_dark.gif
  assets/animations/lottie/breez_loader.lottie
  lib/routes/dev/developers_view.dart
  lib/routes/enter_payment_info/enter_payment_info_page.dart
  lib/routes/home/widgets/bottom_actions_bar/bottom_actions_bar.dart
  lib/routes/home/widgets/payments_filter/widgets/calendar_dialog.dart
  lib/routes/home/widgets/payments_filter/widgets/payment_filter_exporter.dart
  lib/routes/home/widgets/payments_list/widgets/payment_details_sheet/payment_details_sheet.dart
  lib/routes/receive_payment/lightning/receive_lightning_page.dart
  lib/routes/receive_payment/ln_address/receive_lightning_address_page.dart
  lib/routes/receive_payment/lnurl/lnurl_withdraw_page.dart
  lib/routes/receive_payment/onchain/bitcoin_address/receive_bitcoin_address_payment_page.dart
  lib/routes/receive_payment/widgets/destination_widget/widgets/destination_information.dart
  lib/routes/receive_payment/widgets/destination_widget/widgets/update_ln_address_username_bottom_sheet.dart
  lib/routes/security/widgets/security_pin_interval.dart
  lib/routes/send_payment/chainswap/send_chainswap_form.dart
  lib/routes/send_payment/chainswap/send_chainswap_form_page.dart
  lib/routes/send_payment/lightning/ln_invoice_payment_page.dart
  lib/routes/send_payment/lightning/ln_offer_payment_page.dart
  lib/routes/send_payment/lnurl/lnurl_payment_page.dart
  lib/theme/src/breez_dark_theme.dart
  lib/theme/src/custom_theme_data.dart
  lib/widgets/amount_form_field/amount_form_field.dart
  lib/widgets/amount_form_field/currency_converter_bottom_sheet.dart
  lib/widgets/payment_status_sheets/payment_received_sheet.dart
  lib/widgets/payment_status_sheets/payment_sent_sheet.dart
  lib/widgets/payment_status_sheets/processing_payment_sheet.dart
  lib/widgets/payment_status_sheets/redeem_funds_sheet.dart
  lib/widgets/payment_status_sheets/widgets/processing_payment/processing_payment_content.dart
  lib/widgets/shareable_payment_row.dart
Labels: Testing

#426 Add LNURL info and BIP353 address to Liquid payment details
  lib/cubit/payments/models/payment/payment_data.dart
  lib/models/payment_details_extension.dart
  lib/routes/home/widgets/payments_list/widgets/payment_details_sheet/payment_details_sheet.dart
Labels: Testing, Verified

#437 fix: prevent lock screen from getting stuck after PIN deactivation
  lib/cubit/security/security_cubit.dart
  lib/routes/security/lock_screen.dart
  lib/routes/security/secured_page.dart
Labels: Testing, Verified

#439 fix: revert `minSdkVersion` misconfiguration
  .github/workflows/CI.yml
  .github/workflows/build-android.yml
  .github/workflows/build-ios.yml
  android/app/build.gradle
  ios/Podfile.lock
  ios/Runner.xcodeproj/project.pbxproj
  pubspec.lock
  pubspec.yaml
Labels: Testing, High Priority

#454 ui: integrate Lightning invoice flow into Lightning Address page
  ios/Runner.xcodeproj/project.pbxproj
  lib/routes/dev/developers_view.dart
  lib/routes/home/widgets/bottom_actions_bar/widgets/receive_options_bottom_sheet.dart
  lib/routes/receive_payment/ln_address/receive_lightning_address_page.dart
  lib/routes/receive_payment/receive_payment_page.dart
  lib/routes/receive_payment/widgets/payment_message_boxes/payment_limits_message_box.dart
Labels: Testing
