Repository breez/misty-breez, pull requests merged in 2025-02, with the labels that each got.

#348 Handle missing LN Address in webhook recovery by falling back to registration
  lib/cubit/account/account_state.dart
  lib/cubit/ln_address/ln_address_cubit.dart
  lib/routes/home/widgets/payments_list/widgets/payment_details_sheet/widgets/widgets.dart
Labels: Testing, Verified

#363 Add additional logs to `AccountRequiredActionsIndicator`'s
  lib/routes/home/widgets/home_app_bar/widgets/account_required_actions.dart
Labels: High Priority

#364 Store seed verification status locally on `SharedPreferences`
  lib/cubit/security/mnemonic_verification_status_preferences.dart
  lib/cubit/security/security_cubit.dart
  lib/cubit/security/security_state.dart
  lib/routes/home/widgets/home_app_bar/widgets/account_required_actions.dart
  lib/routes/initial_walkthrough/initial_walkthrough_page.dart
  lib/routes/initial_walkthrough/mnemonics/verify_mnemonics_page.dart
  lib/routes/security/widgets/mnemonics/security_mnemonics_management.dart
Labels: Testing, High Priority, Verified

#356 Display BIP 353 Address information on Payment Details
  lib/routes/home/widgets/payments_list/widgets/payment_details_sheet/payment_details_sheet.dart
  lib/routes/home/widgets/payments_list/widgets/payment_details_sheet/widgets/payment_details_sheet_bip_353_address.dart
Labels: Testing, Verified

#355 Add input handing for Bolt 12 Offers & LNURL payments resolved from BIP 353 Address
  lib/app/routes/routes.dart
  lib/cubit/input/input_cubit.dart
  lib/cubit/input/input_state.dart
  lib/handlers/input_handler/src/input_handler.dart
  lib/routes/home/widgets/payments_list/widgets/payment_details_sheet/payment_details_sheet.dart
  lib/routes/home/widgets/payments_list/widgets/payment_details_sheet/widgets/payment_details_sheet_bip_353_address.dart
  lib/routes/lnurl/payment/lnurl_payment_handler.dart
  lib/routes/send_payment/lightning/ln_offer_payment_page.dart
  lib/routes/send_payment/lnurl/lnurl_payment_page.dart
Labels: SDK Integration

#365 Fix UI regression preventing on-chain payment errors from showing
  lib/routes/send_payment/chainswap/widgets/send_chainswap_button.dart
  lib/widgets/payment_status_sheets/processing_payment_sheet.dart
Labels: Testing, High Priority

#360 Fix refund fees validation
  lib/cubit/model/src/fee_option/fee_option.dart
  lib/cubit/refund/refund_cubit.dart
  lib/cubit/refund/refund_state.dart
  lib/models/payment_details_extension.dart
  lib/models/sdk_formatted_string_extensions.dart
  lib/routes/refund/refund_confirmation_page.dart
  lib/routes/send_payment/chainswap/send_chainswap_confirmation_page.dart
Labels: Testing, High Priority

#388 fix: Ensure Share & Copy buttons scale properly on small screens
  lib/routes/receive_payment/widgets/destination_widget/widgets/destination_actions.dart
Labels: Testing

#387 feat: Add `FeeBreakdown` for Refund Fee Options
  lib/routes/refund/refund_confirmation_page.dart
  lib/routes/refund/refund_page.dart
  lib/routes/send_payment/chainswap/widgets/fee/fee_breakdown/fee_breakdown.dart
  lib/routes/send_payment/chainswap/widgets/fee/fee_chooser/fee_chooser.dart
Labels: Testing

#386 Show payment success sheet after completing LN payments
  lib/cubit/input/input_cubit.dart
  lib/handlers/input_handler/src/input_handler.dart
  lib/routes/receive_payment/widgets/destination_widget/destination_widget.dart
  lib/utils/constants.dart
  lib/widgets/payment_status_sheets/payment_received_sheet.dart
  lib/widgets/payment_status_sheets/payment_sent_sheet.dart
  lib/widgets/payment_status_sheets/processing_payment_sheet.dart
Labels: Testing

#399 fix: Preserve user's existing LN address username during device ownership transfer
  lib/cubit/ln_address/ln_address_cubit.dart
Labels: High Priority
