Repository breez/misty-breez, pull requests merged in 2025-04, with the labels that each got.

#499 refactor: replace LnUrlCubit with LnUrlService
  lib/app/view/app.dart
  lib/cubit/cubit.dart
  lib/cubit/lnurl/lnurl_cubit.dart
  lib/cubit/lnurl/lnurl_state.dart
  lib/routes/lnurl/auth/lnurl_auth_handler.dart
  lib/routes/lnurl/payment/lnurl_payment_handler.dart
  lib/routes/receive_payment/lightning/receive_lightning_page.dart
  lib/routes/receive_payment/lnurl/lnurl_withdraw_page.dart
  lib/routes/send_payment/lightning/ln_invoice_payment_page.dart
  lib/routes/send_payment/lightning/ln_offer_payment_page.dart
  lib/routes/send_payment/lnurl/lnurl_payment_page.dart
  lib/services/lnurl_service.dart
  lib/services/services.dart
  lib/widgets/payment_status_sheets/redeem_funds_sheet.dart
Labels: Low Priority

#496 fix: Resolve HydratedBloc persistence issues in obfuscated release builds
  ios/Runner.xcodeproj/project.pbxproj
  lib/cubit/account/account_cubit.dart
  lib/cubit/account/account_state.dart
  lib/cubit/currency/currency_cubit.dart
  lib/cubit/currency/currency_state.dart
  lib/cubit/payments/models/payment/payment_data.dart
  lib/cubit/payments/models/payment/payment_filters.dart
  lib/cubit/payments/payments_cubit.dart
  lib/cubit/payments/payments_state.dart
  lib/cubit/security/security_cubit.dart
  lib/cubit/security/security_state.dart
  lib/cubit/user_profile/user_profile_cubit.dart
  lib/cubit/user_profile/user_profile_state.dart
  lib/main/bootstrap.dart
  lib/main/hydrated_bloc_storage.dart
  lib/main/main.dart
  lib/routes/home/account_page.dart
  lib/utils/enum/enum_utils.dart
  lib/utils/json_parsing/json_parsing.dart
  lib/utils/utils.dart
Labels: Testing, High Priority

#508 BOLT12 receive
  lib/models/extensions/payment_method_extension.dart
  lib/routes/dev/developers_view.dart
  lib/routes/receive_payment/lightning/receive_lightning_page.dart
  lib/routes/receive_payment/ln_address/receive_lightning_address_page.dart
  lib/routes/receive_payment/lnurl/lnurl_withdraw_page.dart
  lib/routes/receive_payment/receive_payment_page.dart
  lib/routes/receive_payment/widgets/payment_method_dropdown/payment_method_dropdown.dart
  lib/routes/send_payment/lightning/ln_invoice_payment_page.dart
  lib/routes/send_payment/lightning/ln_offer_payment_page.dart
  lib/routes/send_payment/lnurl/lnurl_payment_page.dart
  lib/widgets/shareable_payment_row.dart
  pubspec.lock
Labels: Testing
